Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Metrics/ParameterLists:
  Max: 6
Metrics/MethodLength:
  Max: 12
